import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import moment from 'moment';
import { useAppDispatch as oi } from '../hooks/hooks';
import { RootState, AppThunk } from '../reducers/store';
import { api } from '../services/api';

export interface CategoryState {
    value: [
        Category
    ]
    status: 'idle' | 'loading' | 'failed';
}

export interface Category {
    categoryId: number,
    categoryName: string
}

const initialState: CategoryState = {
    value: [
        {
            categoryId: 0,
            categoryName: ''
        }
    ],
    status: 'idle',
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const handleCategory = createAsyncThunk(
    'category',
    async () => {
        const response = await api
            .get(`/category/list`);
        // The value we return becomes the `fulfilled` action payload
        return response.data;
    }
);


export const categorySlice = createSlice({
    name: 'category',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {

    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
            .addCase(handleCategory.pending, (state) => {
                state.status = 'loading';
            })
            .addCase(handleCategory.fulfilled, (state, action) => {
                state.status = 'idle';
                state.value = action.payload;
            })
            .addCase(handleCategory.rejected, (state) => {
                state.status = 'failed';
            });
    },
});

// export const { increment, decrement, incrementByAmount } = balanceSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.balance.value)`
export const selectCategory = (state: RootState) => state.category.value;

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.
// export const incrementIfOdd =
//     (amount: number): AppThunk =>
//         (dispatch, getState) => {
//             const currentValue = selectCount(getState());
//             if (currentValue % 2 === 1) {
//                 dispatch(incrementByAmount(amount));
//             }
//         };

export default categorySlice.reducer;
