import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import moment from 'moment';
import { useAppDispatch as oi } from '../hooks/hooks';
import { RootState, AppThunk } from '../reducers/store';
import { api } from '../services/api';

export interface DebitsState {
    value: {
        detail: {
            totalDebits: number,
            countDebits: number
        },
        debits: [
            Debit
        ]
    }
    status: 'idle' | 'loading' | 'failed';
}

export interface Debit {
    id: number,
    name: string,
    value: number,
    date: string,
    month: number,
    year: number,
    authorId: number,
    categoryId: number
}

const initialState: DebitsState = {
    value: {
        detail: {
            totalDebits: 0,
            countDebits: 0
        },
        debits: [
            {
                id: 0,
                name: '',
                value: 0.0,
                date: '',
                month: 0,
                year: 0,
                authorId: 0,
                categoryId: 0
            }
        ]
    },
    status: 'idle',
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const handleDebit = createAsyncThunk(
    'debit',
    async () => {
        const response = await api
            .get(`/debit/list`);
        // The value we return becomes the `fulfilled` action payload
        return response.data;
    }
);

export const postDebit = async (debit: Debit) => {
    const response = await api
        .post(
            `/debit`,
            debit
        );
    return response.data;
}

export const debitSlice = createSlice({
    name: 'debit',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {

    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
            .addCase(handleDebit.pending, (state) => {
                state.status = 'loading';
            })
            .addCase(handleDebit.fulfilled, (state, action) => {
                state.status = 'idle';
                state.value = action.payload;
            })
            .addCase(handleDebit.rejected, (state) => {
                state.status = 'failed';
            });
    },
});

// export const { increment, decrement, incrementByAmount } = balanceSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.balance.value)`
export const selectDebit = (state: RootState) => state.debit.value;

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.
// export const incrementIfOdd =
//     (amount: number): AppThunk =>
//         (dispatch, getState) => {
//             const currentValue = selectCount(getState());
//             if (currentValue % 2 === 1) {
//                 dispatch(incrementByAmount(amount));
//             }
//         };

export default debitSlice.reducer;
